title: Binary Temple
description: Welcome to the temple, my lord! Contemplate the grandeur of the bits.
author:
  name: Pedro Lima
  email: pedro.lima1979@hotmail.com
  nickname: "@_ordepp"
  twitter: https://twitter.com/_ordepp
  github: https://github.com/boloto1979
  linkedin: https://www.linkedin.com/in/pedro-lima3233/

baseurl: ""
url: https://boloto1979.github.io

nav:
  - title: Home
    path: /
  - title: About
    path: /about

paginate: 3
paginate_path: "/:num"

collections:
  posts:
    output: true
    permalink: "/post/:title"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
